BeltExamProject/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^',include('apps.login.urls',namespace='login')),
    url(r'quotes/',include('apps.quotes.urls', namespace='quotes'))
]

apps/login/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^create_user$',create_user, name='create_user'),
	url(r'^login_user$',login_user, name='login_user')
]

apps/quotes/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'logout$',logout,name='logout'),
	url(r'create_quote$',create_quote,name='create_quote'),
	url(r'show_user/(?P<user_id>\d+)$',show_user,name='show_user'),
	url(r'add_to_favorites/(?P<quote_id>\d+)$',add_to_favorites,name='add_to_favorites'),
	url(r'remove_from_favorites/(?P<quote_id>\d+)$',remove_from_favorites,name='remove_from_favorites')
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class User(models.Model):
	name = models.CharField(max_length=50)
	alias = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	date_of_birth = models.CharField(max_length=50)
	password = models.CharField(max_length=200)
	quote_count = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/quotes/models.py
from __future__ import unicode_literals

from django.db import models
from .. login.models import User

# Create your models here.
class Quote(models.Model):
	author = models.CharField(max_length=50)
	message = models.TextField()
	posted_by = models.ForeignKey(User, related_name='all_my_quotes')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Favorite(models.Model):
	user = models.ForeignKey(User, related_name='user_my_favorites')
	quote = models.ForeignKey(Quote, related_name='quote_my_favorites')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User
import bcrypt, re

# Create your views here.
def index(request):
	return render(request, 'login/index.html')

def new_user(request):
	return render(request, 'login/new_user.html')

def create_user(request):
	name = request.POST['txt_name']
	alias = request.POST['txt_alias']
	email = request.POST['txt_email']
	emailValid = re.search(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$',email)
	date_of_birth = request.POST['txt_date_of_birth']
	password = request.POST['txt_password']
	confirm_pw = request.POST['txt_confirm_password']

	if len(name)<1 or len(alias)<1 or len(email)<1 or len(date_of_birth)<1 or len(password)<1 or len(confirm_pw)<1:
		messages.warning(request,'Please make sure no fields are blank')
		return redirect('login:index')
	elif len(password)<6:
		messages.warning(request, 'password must be at least 6 characters')
		return redirect('login:index')
	elif emailValid == None:
		messages.warning(request, 'invalid email format')
		return redirect('login:index')
	elif password != confirm_pw:
		messages.warning(request,'passwords must match')
		return redirect('login:index')
	else:
		# hash password
		try:
			hashed_pw = bcrypt.hashpw(password.encode("UTF-8"), bcrypt.gensalt())
			print '-' * 50
			print 'hashed_pw:', hashed_pw
			print '-' * 50
			new_user = User.objects.create(name=name,alias=alias,email=email,date_of_birth=date_of_birth,password=hashed_pw,quote_count=0)
			print '-' * 50
			print 'new_user:',new_user
			print '-' * 50
			request.session['user_id'] = new_user.id
			request.session['alias'] = new_user.alias

			messages.success(request,'New user created! Welcome!')
			print 'new user created!'
			return redirect('quotes:index')
		except:
			messages.warning(request, 'hash pword problem')
			return redirect('login:index')
	return redirect('recipes:index')

def login_user(request):
	email = request.POST['txt_email']
	password = request.POST['txt_password']

	if len(email)<1 or len(password)<1:
		messages.warning(request, 'both login fields are required')
		return redirect('login:index')
	elif len(password)<6:
		messages.warning(request, 'password must be at least 6 characters')
		return redirect('login:index')
	else:
		try:
			this_user = User.objects.get(email=email)
			print '-' * 50
			print 'password',this_user.password
			print '-' * 50
			if this_user.password == bcrypt.hashpw(password.encode("UTF-8"),this_user.password.encode("UTF-8")):
				messages.success(request, 'You are logged in!')
				request.session['user_id'] = this_user.id
				request.session['alias'] = this_user.alias

				return redirect('quotes:index')
			else:
				messages.warning(request, 'invalid password, try again')

				return redirect('login:index')
		except:
			messages.warning(request, 'user not found')
			return redirect('login:index')

apps/quotes/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from ..login.models import User
from .models import Quote, Favorite
import bcrypt, re

# Create your views here.
def index(request):
	all_quotes = Quote.objects.all().order_by('-created_at')
	this_user = User.objects.get(id=request.session['user_id'])
	my_favorites = Favorite.objects.filter(user_id=this_user.id).order_by('-created_at')
	
	my_favorite_quotes = []
	favorites_list = []
	for favorite in my_favorites:
		favorites_list.append(favorite.quote.id)
		my_favorite_quotes.append(favorite.quote)
	
	

	context = {
		'all_quotes': all_quotes,
		'favorites_list': favorites_list,
		'my_favorite_quotes': my_favorite_quotes,
		'my_favorites': my_favorites
	}
	return render(request, 'quotes/index.html', context)

def logout(request):
	request.session.clear()
	messages.success(request,'Logged out successfully')
	return redirect('login:index')

def create_quote(request):
	author = request.POST['txt_author']
	message = request.POST['txt_message']
	this_user = User.objects.get(id=request.session['user_id'])

	if len(author)<1 or len(message)<1:
		messages.warning(request, '*both fields are required to contribute a quote')
		return redirect('quotes:index')
	elif len(author)<4:
		messages.warning(request, 'author must be at least 4 characters long')
		return redirect('quotes:index')
	elif len(message)<11:
		messages.warning(request, 'Message must be more than 10 characters')
		return redirect('quotes:index')
	else:
		new_quote = Quote.objects.create(author=author,message=message,posted_by=this_user)
		this_user.quote_count += 1
		this_user.save()
		messages.success(request, 'New quote created!')
		return redirect('quotes:index')

def show_user(request,user_id):
	this_user = User.objects.get(id=user_id)
	my_quotes = Quote.objects.filter(posted_by=user_id)

	context = {
		'this_user': this_user,
		'my_quotes': my_quotes
	}
	return render(request, 'quotes/show_user.html', context)

def add_to_favorites(request, quote_id):
	this_user = User.objects.get(id=request.session['user_id'])
	this_quote = Quote.objects.get(id=quote_id)

	new_favorite = Favorite.objects.create(user=this_user,quote=this_quote)
	messages.success(request, 'Quote has been favorited!')

	return redirect('quotes:index')

def remove_from_favorites(request,quote_id):
	user_id = request.session['user_id']
	this_quote = Quote.objects.get(id=quote_id)
	this_user = User.objects.get(id=request.session['user_id'])

	
	this_favorite = Favorite.objects.filter(user=user_id,quote=quote_id)
	print 'favorite to delete:',this_favorite[0].id
	this_favorite.delete()

	messages.success(request, 'Quote removed from favorites')

	return redirect('quotes:index')

apps/login/templates/login/header.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet"> 
	 {% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}">
</head>
<body>
{% if messages %}
	{% for message in messages %}
		<p>{{message}}</p>
	{% endfor %}
{% endif %}

apps/login/templates/login/index.html
{% include 'login/header.html' %}
	<div id="container">
		<!-- Register form -->
		<form id="register_form" action="{% url 'login:create_user' %}" method="post">
			{% csrf_token %}
			<fieldset>
				<legend>Register</legend>
				<table>
					<tr>
						<td>Name:</td><td><input type="text" name="txt_name" >*</td>
					</tr>
					<tr>
						<td>Alias:</td><td><input type="text" name="txt_alias">*</td>
					</tr>
					<tr>
						<td>E-mail:</td><td><input type="text" name="txt_email" >*</td>
					</tr>
					<tr>
						<td>Date of Birth:</td><td><input type="text" name="txt_date_of_birth" >*</td>
					</tr>
					<tr>
						<td>Password:</td><td><input type="password" name="txt_password" >*</td>
					</tr>
					<tr>
						<td>Confirm password:</td><td><input type="password" name="txt_confirm_password" >*</td>
					</tr>
				</table>
				<input class="button" type="submit" value="Register">
			</fieldset>
		</form>

			<!-- Login form -->
			<form id="login_form" action="{% url 'login:login_user' %}" method="post">
				{% csrf_token %}
				<fieldset>
					<legend>Log In</legend>
					<table>
						<tr>
							<td>E-mail:</td><td><input type="text" name="txt_email">*</td>
						</tr>
						<tr>
							<td>Password:</td><td><input type="password" name="txt_password">*</td>
						</tr>
					</table>
					<input class="button" type="submit" value="Log In">
				</fieldset>
			</form>
	</div>

</body>
</html>

apps/quotes/templates/quotes/header.html
<!DOCTYPE html>
<html>
<head>
	<title>Quotes</title>
	<link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet"> 
	 {% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'quotes/style.css' %}">
</head>
<body>

{% if messages %}
	{% for message in messages %}
		<p>{{message}}</p>
	{% endfor %}
{% endif %}

apps/quotes/templates/quotes/index.html
{% include 'quotes/header.html' %}
	<div id="container">
		<a href="{% url 'quotes:logout' %}">Logout</a>
		<h1>Welcome {{request.session.alias}}!</h1>

		<div id="all_quotes">
			<h2>Quotable Quotes</h2>
			{% for quote in all_quotes %}
				{% if quote.id in favorites_list %}
					<!-- Already a favorite -->
				{% else %}
					<div class="general_quote">
						<span class="author">{{quote.author}}</span>:
						&nbsp;{{quote.message}}
						<br><br>
						<i class="posted_by">Posted by <a href="{% url 'quotes:show_user' user_id=quote.posted_by.id %}"> {{quote.posted_by.alias}}</a></i>
						<br>
						<a class="button" href="{% url 'quotes:add_to_favorites' quote_id=quote.id %}">Add to My Favorites</a>
					</div>
				{% endif %}		
				
			{% endfor %}
		</div> <!-- #all_quotes -->

		<div id="favorite_quotes">
			
			<h2>Your Favorites</h2>
			{% for quote in my_favorite_quotes %}
				<div class="one_quote">
					<span class="author">{{quote.author}}</span>:
					{{quote.message}}
					<br><br>
					<i>Posted by <a href="{% url 'quotes:show_user' user_id=quote.posted_by.id %}"> {{quote.posted_by.alias}}</a></i>
					<br>
					<a class="button" href="{% url 'quotes:remove_from_favorites' quote_id=quote.id %}">Remove from My Favorites</a>
					
				</div>
			{% endfor %}
			<div class="favorite_quote">
				
			</div>
		</div> <!-- #favorite_quotes -->

		<!-- Contribute a Quote -->
		<div id="new_quote_form">
			<form action="{% url 'quotes:create_quote' %}" method="post">
				{% csrf_token %}
				<h2>Contribute a Quote</h2>
				<label>Quoted By:</label><input type="text" name="txt_author"><br>
				<label>Message:</label><textarea name="txt_message"></textarea><br>
				<br>
				<input class="button" type="submit" value="Submit">

			</form>
		</div>
	</div> <!-- #container -->


</body>
</html>

apps/quotes/templates/quotes/show_user.html
{% include 'quotes/header.html' %}
	<div id="container">
		<nav>
			<a href="{% url 'quotes:index' %}">Dashboard</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="{% url 'quotes:logout' %}">Logout</a>
		</nav>

		<h3>Posts by {{this_user.alias}}</h3>
		<h3>Count: {{this_user.quote_count}}</h3>

		{% for quote in my_quotes %}
			<p>
				<span class="green">{{quote.author}}</span>:
				{{quote.message}}
			</p>
		{% endfor %}
	</div>

</body>
</html>